### ISSUE TITLE
Potential bug in the Model-as-image example in tutorial

### ISSUE THREAD

**Issue by sriumcp** [GoogleCloudPlatform/ai-on-gke#1071]
I have a question re: this tutorial: https://github.com/GoogleCloudPlatform/ai-on-gke/tree/main/tutorials-and-examples/models-as-oci

It presents the following snippet of code as the `model-as-image` approach in GCP.

```yaml
initContainers:
  - name: model
    image: model-as-image
    restartPolicy: Always
    args:
    - "sh"
    - "-c"
    - "ln -s /model /mnt/model && sleep infinity"
    volumeMounts:
    - mountPath: /mnt/model
      name: model-image-mount
      readOnly: False
volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: llama3-model
    emptyDir: {}
```

The `sleep infinity` above ensures that the initContainer never exits, and the main `vllm` container never starts.

Isn't this a bug? Or did I misunderstand?
