### ISSUE TITLE
Add more resources for Jupyterhub Profiles

### ISSUE THREAD

**Issue by chiayi** [GoogleCloudPlatform/ai-on-gke#67]
Currently the resources per Jupyterhub Profile is 
```
cpu:
    limit: .5
    guarantee: .5
  memory:
    limit: 1G
    guarantee: 1G
```

And it should be increased
